environment: development
package:
  authors:
    - Tatsuya Koishi
  description: Nagios形式の監視プラグインを実行する簡易なサービス。
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
  url: https://github.com/pooza/paprika
  version: 1.0.0
puma:
  pidfile: tmp/pids/puma.pid
  port: 3011
  rackup: app/initializer/config.ru
  threads: 5
  workers: 0
